
mkdir -p ${RISCV_ZUAN_BUILD_DIR}
cd ${RISCV_ZUAN_BUILD_DIR}

PATH=${RISCV_GNU_TOOLCHAIN_DIR}/bin:${PATH} \
cmake -G Ninja .. \
    -DCMAKE_SYSTEM_NAME=Linux \
    -DCMAKE_SYSTEM_PROCESSOR=riscv64 \
    -DMLIR_DIR=${RISCV_LLVM_BUILD_DIR}/lib/cmake/mlir \
    -DLLVM_DIR=${RISCV_LLVM_BUILD_DIR}/lib/cmake/llvm \
    -DCMAKE_CROSSCOMPILING=True \
    -DCMAKE_CROSSCOMPILING_EMULATOR=qemu-riscv64 \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_NATIVE_ARCH=RISCV \
    -DLLVM_HOST_TRIPLE=riscv64-unknown-linux-gnu \
    -DCMAKE_C_COMPILER=${HOST_LLVM_BUILD_DIR}/bin/clang \
    -DCMAKE_CXX_COMPILER=${HOST_LLVM_BUILD_DIR}/bin/clang++ \
    -DCMAKE_C_FLAGS="--target=riscv64-unknown-linux-gnu --sysroot=${RISCV_GNU_TOOLCHAIN_SYSROOT_DIR} --gcc-toolchain=${RISCV_GNU_TOOLCHAIN_DIR}" \
    -DCMAKE_CXX_FLAGS="--target=riscv64-unknown-linux-gnu --sysroot=${RISCV_GNU_TOOLCHAIN_SYSROOT_DIR} --gcc-toolchain=${RISCV_GNU_TOOLCHAIN_DIR}" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DENABLE_BENCHMARKS=ON \
    -DENABLE_TRITON_BENCHMARKS=${ENABLE_TRITON_BENCHMARKS:-ON} \
    ${ZUAN_TRITON_PYTHON_EXECUTABLE:+-DZUAN_TRITON_PYTHON_EXECUTABLE=${ZUAN_TRITON_PYTHON_EXECUTABLE}} \
    ${ZUAN_TRITON_CPU_OPT:+-DZUAN_TRITON_CPU_OPT=${ZUAN_TRITON_CPU_OPT}} \
    ${ZUAN_TRITON_SHARED_OPT:+-DZUAN_TRITON_SHARED_OPT=${ZUAN_TRITON_SHARED_OPT}} \
    ${ZUAN_TRITON_LLVM_BINARY_DIR:+-DZUAN_TRITON_LLVM_BINARY_DIR=${ZUAN_TRITON_LLVM_BINARY_DIR}} \
    ${ZUAN_TRITON_CPU_LLVM_BINARY_DIR:+-DZUAN_TRITON_CPU_LLVM_BINARY_DIR=${ZUAN_TRITON_CPU_LLVM_BINARY_DIR}} \
    -DPython3_EXECUTABLE=$(which python3)

ninja
