# Cross Compiled MLIR
mkdir -p ${RISCV_LLVM_BUILD_DIR}
cd ${RISCV_LLVM_BUILD_DIR}
PATH=${RISCV_GNU_TOOLCHAIN_DIR}/bin:${PATH} \
cmake -G Ninja ../llvm \
    -DCMAKE_SYSTEM_NAME=Linux \
    -DCMAKE_SYSTEM_PROCESSOR=riscv64 \
    -DLLVM_ENABLE_PROJECTS="mlir" \
    -DLLVM_TARGETS_TO_BUILD="RISCV" \
    -DLLVM_BUILD_EXAMPLES=OFF \
    -DCMAKE_CROSSCOMPILING=True \
    -DCMAKE_CROSSCOMPILING_EMULATOR=qemu-riscv64 \
    -DLLVM_TARGET_ARCH=RISCV64 \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DLLVM_NATIVE_ARCH=RISCV \
    -DLLVM_HOST_TRIPLE=riscv64-unknown-linux-gnu \
    -DLLVM_DEFAULT_TARGET_TRIPLE=riscv64-unknown-linux-gnu \
    -DLLVM_NATIVE_TOOL_DIR=${HOST_LLVM_BUILD_DIR}/bin \
    -DCMAKE_C_COMPILER=${HOST_LLVM_BUILD_DIR}/bin/clang \
    -DCMAKE_CXX_COMPILER=${HOST_LLVM_BUILD_DIR}/bin/clang++ \
    -DCMAKE_C_FLAGS="--target=riscv64-unknown-linux-gnu --sysroot=${RISCV_GNU_TOOLCHAIN_SYSROOT_DIR} --gcc-toolchain=${RISCV_GNU_TOOLCHAIN_DIR}" \
    -DCMAKE_CXX_FLAGS="--target=riscv64-unknown-linux-gnu --sysroot=${RISCV_GNU_TOOLCHAIN_SYSROOT_DIR} --gcc-toolchain=${RISCV_GNU_TOOLCHAIN_DIR}" \
    -DLLVM_ENABLE_ZSTD=Off

ninja
